import { useState } from 'react';
import './Roadmap.css'
function Roadmap() {
  const [activebutton,setActiveButton]=useState(null);
  const handleClick=(index)=>{
    setActiveButton(index);
  }
  
  return (
    <div className='road-map' id='roadmap'>
        <div className="container">
            <div className="road-head">Roadmap</div>{/**"road-head" */}
            <ul className='slides'>
                <li className={`slide${ activebutton ===0? ' active':'' }`}>
                <div  className="action" onClick={()=>handleClick(0)} ><span >Phase I</span>
                </div>
                 <div className="slide-content">
                  <h4>Phase I</h4>
                  <h2>Market Research</h2>
                  <p> Orion Crypto begun conducting market research on the potential of Actively Managed Certificates (AMC) and incorporating a crypto element. AMC’s are designed to allow investors to invest in any digital asset without having to buy into the actual cryptocurrency itself. With the AMC Orion Crypto seeks to offer investors diversification and investment flexibility with its state-of-the-art technology. By leveraging the AMC, Orion Crypto will be enabling customers to access global markets more effectively from one account, giving them more control over their investments and allowing them more freedom when it comes to deciding which cryptocurrencies they want to include in their portfolio. The AMC offers a unique melding of access, control and convenience that can be tailored for each investor's needs; it is this aspect that Orion is hoping to enhance by integrating its cutting-edge technology and extensive market experience into the AMC framework.</p></div>
                
                </li>
                
                <li className={`slide${ activebutton ===1? ' active':'' }`} >
                  <div className="action" onClick={()=>handleClick(1)} ><span>Phase II</span>
                </div>
                  <div className="slide-content" ><h4>Phase II</h4><h2>ORION CRYPTO AMC FORMATION + LISTING</h2><p> Orion Crypto is thrilled to announce the listing of its Orion Crypto Actively Managed Certificate. Orion Crypto has become a leader in the burgeoning crypto market with its innovative, modern approach to investments. Investors can now take even more advantage of Orion Crypto's secure platform that provides access to regulated digital assets in forms suited to their needs. Orion will continue to deliver an unmatched trading experience and commitment to financial freedom that is at the core of its mission.</p></div></li> 

                <li  className={`slide${ activebutton ===2? ' active':'' }`} ><div className="action" onClick={()=>handleClick(2)}><span>Phase III</span></div><div className="slide-content" ><h4>Phase III</h4><h2>ORION CRYPTO LTD FORMATION</h2><p> Orion Crypto is leading the blockchain revolution with its Orion Crypto Actively Managed Certificate. This limited company formation enables investors to access Orion's expert team of financial professionals through an actively managed structure, allowing Orion to apply a powerful mix of AI strategies and technical analysis to generate returns in the cryptocurrency markets. Orion puts its trust in the best available research and data-driven technology, ensuring maximum transparency for investors. Through this innovative approach, Orion brings a unique edge to his clients' investments that cannot be found elsewhere.</p></div></li>
                <li  className={`slide${ activebutton ===3? ' active':'' }`}><div className="action"  onClick={()=>handleClick(3)}><span>Phase IV</span></div><div className="slide-content" ><h4>Phase IV</h4><h2>ORION CRYPTO PRESALE STARTS</h2><p> Orion Crypto has recently announced the launch of its crypto token presale, £ORION$, to further enhance its suite of financial instruments. It aims to become the world’s first User-Centric Actively Managed Certificate (AMC) Ecosystem. Orion Crypto will allow users to access a wider range of tokenized financial instruments such as accessible options for investments and management of funds in cryptocurrency. Orion Crypto offers an alternate asset class that is currently unavailable in traditional banking or stock markets. The Orion Crypto Token Presale will allow investors to capitalize on tokenizing various products and services while allowing Orion Crypto customers to manage their wealth securely without any middleman or third-party interference. This new product seeks to bridge the gap between traditional banking systems and today’s digital economy by offering an unrivalled platform for capital growth and security</p></div></li>

               
                <li className={`slide${ activebutton ===4? ' active':'' }`}><div className="action"onClick={()=>handleClick(4)}><span>Phase V</span></div><div className="slide-content" ><h4>Phase V</h4><h2>ORION CRYPTO INTERACTIVE DAPP ACTIVATED</h2><p> Orion Crypto is proud to introduce its interactive Dapp, designed to provide users with the features they need to take control of their finances. Orion Crypto delivers actively managed certificates that give investors direct access to cryptocurrency trading and global markets. Orion's solution will make it easier for its users to monitor, track, and maximise their investments by giving them greater control of their funds. Through Orion's cutting-edge technology, users can continually stay ahead of changing market conditions and be able to respond with near real-time precision in making investment decisions. Orion Crypto is looking forward for everyone who wants access to innovative financial products and comprehensive trading solutions in one place.</p></div></li>
                <li className={`slide${ activebutton ===5? ' active':'' }`}><div className="action"onClick={()=>handleClick(5)}><span>Phase VI</span></div><div className="slide-content" ><h4>Phase VI</h4><h2>ORION CRYPTO PRESALE ENDS</h2><p>Orion Crypto recently concluded their Presale and the results have been overwhelmingly positive. Orion Crypto provides institutional investors with an Active Managed Certificate (AMC). This digital asset is a tangible arbitrage-based portfolio which allows for consistent returns without needing frequent monitoring or trading activity. Those that participated in Orion Crypto's Presale were able to get tremendous savings on the AMC, but with the Presale now coming to an end, those looking to take advantage of this unique opportunity need to act fast. Orion Crypto will continue offering AMCs for investors, but without the pre-sale discount. Make sure to act quickly if you want the chance to gain from Orion Crypto's ground-breaking financial technology features!</p></div></li>
                <li className={`slide${ activebutton ===6? ' active':'' }`}><div className="action"  onClick={()=>handleClick(6)}><span>Phase VII</span></div><div className="slide-content" ><h4>Phase VII</h4><h2>ORION CRYPTO PUBLIC LAUNCH </h2><p>Orion Crypto has launched their £ORION$ token which is tied to an Actively Managed Certificate. With this new token Orion Crypto is offering the general public the chance to participate in a public sale and enter the cryptocurrency market in an innovative way. The £ORION$ token further expands Orion Crypto's portfolio, enabling more individuals to become part of a crypto-driven future. Orion Crypto has always been focused on redefining investing and with this new deployment they are moving closer towards achieving that goal.</p></div></li>
                <li className={`slide${ activebutton ===7? ' active':'' }`}><div className="action"  onClick={()=>handleClick(7)}><span>Phase VIII</span></div><div className="slide-content" ><h4>Phase VIII</h4><h2>ORION CRYPTO PUBLIC LAUNCH </h2><p>Orion Crypto has launched their £ORION$ token which is tied to an Actively Managed Certificate. With this new token Orion Crypto is offering the general public the chance to participate in a public sale and enter the cryptocurrency market in an innovative way. The £ORION$ token further expands Orion Crypto's portfolio, enabling more individuals to become part of a crypto-driven future. Orion Crypto has always been focused on redefining investing and with this new deployment they are moving closer towards achieving that goal.</p></div></li>
                <li className={`slide${ activebutton ===8? ' active':'' }`}>
                    <div className="action"  onClick={()=>handleClick(8)}><span>Phase IX</span></div>
                    <div className="slide-content">
                        <h4>Phase IX</h4>
                        <h2>Market Research</h2>
                        <p> Orion Crypto begun conducting market research on the potential of Actively Managed Certificates (AMC) and incorporating a crypto element. AMC’s are designed to allow investors to invest in any digital asset without having to buy into the actual cryptocurrency itself. With the AMC Orion Crypto seeks to offer investors diversification and investment flexibility with its state-of-the-art technology. </p>
                        <p>By leveraging the AMC, Orion Crypto will be enabling customers to access global markets more effectively from one account, giving them more control over their investments and allowing them more freedom when it comes to deciding which cryptocurrencies they want to include in their portfolio. The AMC offers a unique melding of access, control and convenience that can be tailored for each investor's needs; it is this aspect that Orion is hoping to enhance by integrating its cutting-edge technology and extensive market experience into the AMC framework.</p>
                    </div>
                </li>
                <li className={`slide${ activebutton ===9? ' active':'' }`}><div className="action"  onClick={()=>handleClick(9)}><span>Phase X</span></div><div className="slide-content" ><h4>Phase X</h4><h2> NEW AMC INVESTMENTS LAUNCHED</h2><p>Orion Crypto, a pioneering decentralized finance protocol has unveiled a new product to its offering - the Orion Actively Managed Certificate. Orion's Actively Managed Certificates offer automated exposure to yield-bearing DeFi protocols and are explicitly designed for non-technical users. This ground-breaking product is available for public sale this month and can be purchased with Orion's native token, £ORION$. Orion Crypto has democratised access to sophisticated investment opportunities in DeFi space and this initiative is yet another feather in Orion Crypto's cap. With Orion's Actively Managed Certificate, users can easily acquire passive income flows from their investments across various markets faster than ever before.</p></div></li>
                <li className={`slide${ activebutton ===10? ' active':'' }`}><div className="action"  onClick={()=>handleClick(10)}><span>Phase XI</span></div><div className="slide-content" ><h4>Phase XI</h4><h2>FIRST Q1 AUDIT</h2><p>Orion Crypto are excited to report on their first quarter audit since launching an Actively Managed Certificate. Orion Crypto have seen a healthy uptick in interest since its public sale of £ORION$. Orion Crypto expect to increase their exposure over the next quarter, and are confident that their cutting-edge technology and roadmap for success will make them one of the premier crypto companies in the world. Orion Crypto are eager to continue building relationships with current and prospective clients as they work towards further growth. </p></div></li>
                <li className={`slide${ activebutton ===11? ' active':'' }`}><div className="action"  onClick={()=>handleClick(11)}><span>Phase XII</span></div><div className="slide-content" ><h4>Phase XII</h4><h2>ORION CRYPTO NFT LAUNCH </h2><p>Orion Crypto is excited to announce the launch of its Non Fungible Token (NFT). Orion Crypto's NFT comes with an actively managed certificate and allows Orion's clients to invest in and manage their blockchain-based assets securely while staying compliant with regulations. Through Orion's platform, investors can track the performance, trends and transactions of each asset and monitor transactions as they occur. Orion is changing the way people invest and manage their digital assets and continuing to demonstrate their commitment to customer service. With Orion Crypto's NFT, customers are able to diversify their investments more safely than ever before. </p></div></li> 
                <li className={`slide${ activebutton ===12? ' active':'' }`}><div className="action"  onClick={()=>handleClick(12)}><span>Phase XIII</span></div><div className="slide-content"><h4>Phase XIII</h4><h2>ORION CRYPTO'S FIRST ANNUAL MEETING HELD</h2><p>Orion Crypto is hosting its first annual meeting in the upcoming year and is looking forward to a positive event. Orion Crypto offers their clients an Actively Managed Certificate (AMC) which allows them to invest in a variety of leading digital assets. At Orion Crypto's annual meeting, the AMC will be at the forefront as Orion provides presentations on how clients can make the most out of their investment opportunities. Orion plans to make this an engaging occasion with representatives ready to answer any questions that might appear. The Orion team has already started preparing for what is promised to be beneficial and informative event. </p></div></li>
                <li className={`slide${ activebutton ===13? ' active':'' }`}><div className="action"  onClick={()=>handleClick(13)}><span>Phase XIV</span></div><div className="slide-content"><h4>Phase XIV</h4><h2>ORION CRYPTO AMC MEET &amp; GREET (EXCLUSIVE TO PRE-LAUNCH INVESTORS)</h2><p>Orion Crypto is keen to reward our pre-launch investors for their support, and as a special thank you we will be hosting an exclusive meet &amp; greet event in the coming weeks. Investing in Orion Crypto's Actively Managed Certificate has never been more beneficial, and this is your chance to hear from the team directly about our upcoming launches. With Orion Crypto's future innovations on the horizon, this could be your window of opportunity to get in at the ground level of a revolutionary project. We hope you can join us and together we can create a brighter tomorrow with Orion Crypto.</p></div></li>
  <li className={`slide${ activebutton ===14? ' active':'' }`}><div className="action"  onClick={()=>handleClick(14)}><span>Phase XV</span></div><div className="slide-content"><h4>Phase XV</h4><h2>ORION CRYPTO AMC DUBAI PERFORMANCE PARTY</h2><p>Orion Crypto is thrilled to announce an exclusive performance party, coming soon to Dubai. Open to Orion Crypto's community of investors and supporters, this event will be a celebration of Orion Crypto's successful launch of their Actively Managed Certificate (AMC). Orion Crypto has sent out invitations and hopes that their guests will be warmly welcomed by the vibrant city of Dubai. Guests will enjoy personalized performances, authentic cuisine and unforgettable memories with family and friends at Orion Crypto's performance party. With the mission to make buying crypto assets the easiest, best experience possible for its users, Orion Crypto looks forward to meeting everyone in Dubai for this once-in-a-lifetime event! </p></div></li>

            </ul>
            </div>{/**"container" */}
      
    </div>
  )
}

export default Roadmap
